server:
  port: 8888
  
spring:  cloud:    config:      server:          git:            uri: https://github.com/cleitondantas/cursos-alura
            search-paths: MicroservicesComSpringCloud/microservices-repo/fornecedor, MicroservicesComSpringCloud/microservices-repo/loja, MicroservicesComSpringCloud/microservices-repo/transportador